name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.11'
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      
      - name: Cache Julia packages
        uses: julia-actions/cache@v1
        
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
        
      - name: Run tests
        uses: julia-actions/julia-runtest@v1